# Generated by Django 4.1 on 2024-03-24 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLibrary',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(help_text='Please enter the song name', max_length=100)),
                ('music_category', models.CharField(help_text='Please enter the music category', max_length=100)),
                ('singer_name', models.CharField(help_text='Please enter the singer name', max_length=100)),
                ('issue_date', models.DateField(help_text='Please enter the issue date of the song')),
                ('audio_frequency', models.CharField(help_text='Please enter the audio frequency', max_length=100)),
                ('cover', models.ImageField(blank=True, help_text='Please upload the cover image', null=True, upload_to='song_covers/')),
                ('video', models.FileField(blank=True, help_text='Please upload the video file', null=True, upload_to='song_videos/')),
                ('lyric', models.TextField(help_text='Please enter the lyrics')),
                ('intro', models.TextField(help_text='Please enter the song introduction')),
                ('hits', models.IntegerField(default=0, help_text='Please enter the number of hits')),
                ('praise_len', models.IntegerField(default=0, help_text='Please enter the number of likes')),
                ('recommend', models.IntegerField(default=0, help_text='Please enter the recommendation index')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Please enter the creation time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Please enter the last update time')),
                ('singer_id', models.ForeignKey(help_text='Please enter the singer ID', on_delete=django.db.models.deletion.CASCADE, to='Singer.singer')),
            ],
        ),
    ]
