# Generated by Django 4.1 on 2024-03-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum_Classification',
            new_name='ForumClassification',
        ),
    ]
