# Generated by Django 4.1 on 2024-04-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song',
            new_name='player',
        ),
    ]
