# Generated by Django 4.1 on 2024-03-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(help_text='Please enter the gender', max_length=100)),
                ('age', models.IntegerField(default=0, help_text='Please enter the age')),
                ('login_state', models.CharField(help_text='Please enter the user state', max_length=100)),
                ('phone', models.CharField(help_text='Please enter the phone number', max_length=100)),
                ('username', models.CharField(help_text='Please enter the username', max_length=100)),
                ('nickname', models.CharField(help_text='Please enter the nickname', max_length=100)),
                ('password', models.CharField(help_text='Please enter the password', max_length=100)),
                ('email', models.EmailField(help_text='Please enter the email', max_length=254)),
                ('avatar', models.ImageField(blank=True, help_text='Please upload the avatar', null=True, upload_to='avatars/')),
                ('birthday', models.DateField(help_text="Please enter the user's birthday")),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Please enter the account creation time')),
                ('examine_state', models.IntegerField(default=0, help_text='Please enter if it has been registered')),
            ],
        ),
    ]
