# Generated by Django 4.1 on 2024-03-23 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Please enter the singer's name", max_length=100)),
                ('artist_name', models.CharField(help_text="Please enter the singer's name", max_length=100)),
                ('birthday', models.DateField(help_text="Please enter the singer's birthday")),
                ('native_place', models.CharField(help_text='Please enter the singer’s birthplace', max_length=100)),
                ('artist_photos', models.ImageField(blank=True, help_text='Please upload singer photo', null=True, upload_to='artist_photos/')),
                ('represent_music', models.CharField(help_text="Please enter the singer's masterpiece", max_length=100)),
                ('introduction_of_singer', models.TextField(help_text='Please enter the singer introduction')),
                ('hits', models.IntegerField(default=0, help_text='Please enter the singer clicks')),
                ('praise_len', models.IntegerField(default=0, help_text='Please enter the number of likes the singer received')),
                ('recommend_index', models.IntegerField(default=0, help_text='Please enter the singer recommendation index')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Please enter the creation time')),
                ('updatetime', models.DateTimeField(auto_now=True, help_text='Please enter the last update time')),
            ],
        ),
    ]
